cmake_minimum_required(VERSION 3.8)
project(traffic_map)
set(CMAKE_CXX_STANDARD 17)
add_compile_options(-Wall -Wextra -Wpedantic)
find_package(ament_cmake REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(visualization_msgs REQUIRED)
find_package(pugixml REQUIRED)
find_package(OpenMP)
add_library(map_parser src/parser.cpp src/map_processor.cpp)
target_include_directories(map_parser PUBLIC src)
target_link_libraries(map_parser pugixml::pugixml)
if(OpenMP_CXX_FOUND)
  target_link_libraries(map_parser OpenMP::OpenMP_CXX)
endif()
add_executable(road_visualization src/road_visualization.cpp src/lane.cpp)
target_include_directories(road_visualization PRIVATE src)
target_link_libraries(road_visualization map_parser)
ament_target_dependencies(road_visualization geometry_msgs rclcpp sensor_msgs tf2_ros visualization_msgs)
install(TARGETS road_visualization DESTINATION lib/${PROJECT_NAME})
install(FILES src/bjb_sangjani_full.xodr DESTINATION share/${PROJECT_NAME}/maps)
install(DIRECTORY rviz DESTINATION share/${PROJECT_NAME})
ament_package()
